-- MySQL Script generated by MySQL Workbench
-- Tue Dec 16 23:52:01 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sistema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistema` DEFAULT CHARACTER SET utf8 ;
USE `sistema` ;

-- -----------------------------------------------------
-- Table `sistema`.`paguamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`paguamento` (
  `id_paguamento` INT NOT NULL AUTO_INCREMENT,
  `agendamento_id` DECIMAL(45) NULL,
  `forma_paguamento` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `data_paguamento` DATETIME NULL,
  PRIMARY KEY (`id_paguamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema`.`agendamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`agendamento` (
  `id_agendamento` INT NOT NULL,
  `cliente_id` VARCHAR(45) NOT NULL,
  `servico_id` VARCHAR(45) NOT NULL,
  `data` DATE NULL,
  `paguamento_id_paguamento` INT NOT NULL,
  PRIMARY KEY (`id_agendamento`, `cliente_id`, `servico_id`),
  INDEX `fk_agendamento_paguamento1_idx` (`paguamento_id_paguamento`),
  CONSTRAINT `fk_agendamento_paguamento1`
    FOREIGN KEY (`paguamento_id_paguamento`)
    REFERENCES `sistema`.`paguamento` (`id_paguamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`Usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NULL,
  `email` VARCHAR(100) NULL,
  `senha` VARCHAR(60) NULL,
  `telefone` INT NULL,
  `agendamento_id_agendamento` INT NOT NULL,
  `agendamento_cliente_id` VARCHAR(45) NOT NULL,
  `agendamento_servico_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_Usuarios_agendamento1_idx` (`agendamento_id_agendamento` , `agendamento_cliente_id` , `agendamento_servico_id` ) ,
  CONSTRAINT `fk_Usuarios_agendamento1`
    FOREIGN KEY (`agendamento_id_agendamento` , `agendamento_cliente_id` , `agendamento_servico_id`)
    REFERENCES `sistema`.`agendamento` (`id_agendamento` , `cliente_id` , `servico_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`Clientes` (
  `id_clientes` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `email` VARCHAR(100) NULL,
  `senha` VARCHAR(45) NULL,
  `cpf` VARCHAR(14) NULL,
  `agendamento_id_agendamento` INT NOT NULL,
  `agendamento_cliente_id` VARCHAR(45) NOT NULL,
  `agendamento_servico_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_clientes`, `agendamento_id_agendamento`, `agendamento_cliente_id`, `agendamento_servico_id`),
  INDEX `fk_Clientes_agendamento_idx` (`agendamento_id_agendamento` , `agendamento_cliente_id` , `agendamento_servico_id` ) ,
  CONSTRAINT `fk_Clientes_agendamento`
    FOREIGN KEY (`agendamento_id_agendamento` , `agendamento_cliente_id` , `agendamento_servico_id`)
    REFERENCES `sistema`.`agendamento` (`id_agendamento` , `cliente_id` , `servico_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema`.`servicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`servicos` (
  `id_servicos` INT NOT NULL AUTO_INCREMENT,
  `receita_medica` VARCHAR(120) NULL,
  `exames` VARCHAR(45) NULL,
  `consulta` VARCHAR(45) NULL,
  `cerugia` VARCHAR(45) NULL,
  `agendamento_id_agendamento` INT NOT NULL,
  `agendamento_cliente_id` VARCHAR(45) NOT NULL,
  `agendamento_servico_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_servicos`),
  INDEX `fk_servicos_agendamento1_idx` (`agendamento_id_agendamento` , `agendamento_cliente_id` , `agendamento_servico_id` ) ,
  CONSTRAINT `fk_servicos_agendamento1`
    FOREIGN KEY (`agendamento_id_agendamento` , `agendamento_cliente_id` , `agendamento_servico_id`)
    REFERENCES `sistema`.`agendamento` (`id_agendamento` , `cliente_id` , `servico_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema`.`Usuarios_has_servicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`Usuarios_has_servicos` (
  `Usuarios_id_usuario` INT NOT NULL,
  `servicos_id_servicos` INT NOT NULL,
  PRIMARY KEY (`Usuarios_id_usuario`, `servicos_id_servicos`),
  INDEX `fk_Usuarios_has_servicos_servicos1_idx` (`servicos_id_servicos` ) ,
  INDEX `fk_Usuarios_has_servicos_Usuarios1_idx` (`Usuarios_id_usuario` ) ,
  CONSTRAINT `fk_Usuarios_has_servicos_Usuarios1`
    FOREIGN KEY (`Usuarios_id_usuario`)
    REFERENCES `sistema`.`Usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuarios_has_servicos_servicos1`
    FOREIGN KEY (`servicos_id_servicos`)
    REFERENCES `sistema`.`servicos` (`id_servicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
